window.CHAMPION_DATA = {
  source: "LOL.PS",
  sourceUrl: "https://lol.ps/",
  tierlistUrlPattern:
    "https://lol.ps/api/statistics/tierlist.json?region=0&version=145&tier=2&lane={lane}",
  meta: { versionId: 145, description: "26.08", patchDate: "2026-04-15", region: 0, tier: 2 },
  allChampions: [
    { id: "1", name: "애니", nameUs: "Annie" },
    { id: "2", name: "올라프", nameUs: "Olaf" },
    { id: "3", name: "갈리오", nameUs: "Galio" },
    { id: "4", name: "트위스티드 페이트", nameUs: "Twisted Fate" },
    { id: "5", name: "신 짜오", nameUs: "Xin Zhao" },
    { id: "6", name: "우르곳", nameUs: "Urgot" },
    { id: "7", name: "르블랑", nameUs: "LeBlanc" },
    { id: "8", name: "블라디미르", nameUs: "Vladimir" },
    { id: "9", name: "피들스틱", nameUs: "Fiddlesticks" },
    { id: "10", name: "케일", nameUs: "Kayle" },
    { id: "11", name: "마스터 이", nameUs: "Master Yi" },
    { id: "12", name: "알리스타", nameUs: "Alistar" },
    { id: "13", name: "라이즈", nameUs: "Ryze" },
    { id: "14", name: "사이온", nameUs: "Sion" },
    { id: "15", name: "시비르", nameUs: "Sivir" },
    { id: "16", name: "소라카", nameUs: "Soraka" },
    { id: "17", name: "티모", nameUs: "Teemo" },
    { id: "18", name: "트리스타나", nameUs: "Tristana" },
    { id: "19", name: "워윅", nameUs: "Warwick" },
    { id: "20", name: "누누와 윌럼프", nameUs: "Nunu & Willump" },
    { id: "21", name: "미스 포츈", nameUs: "Miss Fortune" },
    { id: "22", name: "애쉬", nameUs: "Ashe" },
    { id: "23", name: "트린다미어", nameUs: "Tryndamere" },
    { id: "24", name: "잭스", nameUs: "Jax" },
    { id: "25", name: "모르가나", nameUs: "Morgana" },
    { id: "26", name: "질리언", nameUs: "Zilean" },
    { id: "27", name: "신지드", nameUs: "Singed" },
    { id: "28", name: "이블린", nameUs: "Evelynn" },
    { id: "29", name: "트위치", nameUs: "Twitch" },
    { id: "30", name: "카서스", nameUs: "Karthus" },
    { id: "31", name: "초가스", nameUs: "Cho'Gath" },
    { id: "32", name: "아무무", nameUs: "Amumu" },
    { id: "33", name: "람머스", nameUs: "Rammus" },
    { id: "34", name: "애니비아", nameUs: "Anivia" },
    { id: "35", name: "샤코", nameUs: "Shaco" },
    { id: "36", name: "문도 박사", nameUs: "Dr. Mundo" },
    { id: "37", name: "소나", nameUs: "Sona" },
    { id: "38", name: "카사딘", nameUs: "Kassadin" },
    { id: "39", name: "이렐리아", nameUs: "Irelia" },
    { id: "40", name: "잔나", nameUs: "Janna" },
    { id: "41", name: "갱플랭크", nameUs: "Gangplank" },
    { id: "42", name: "코르키", nameUs: "Corki" },
    { id: "43", name: "카르마", nameUs: "Karma" },
    { id: "44", name: "타릭", nameUs: "Taric" },
    { id: "45", name: "베이가", nameUs: "Veigar" },
    { id: "48", name: "트런들", nameUs: "Trundle" },
    { id: "50", name: "스웨인", nameUs: "Swain" },
    { id: "51", name: "케이틀린", nameUs: "Caitlyn" },
    { id: "53", name: "블리츠크랭크", nameUs: "Blitzcrank" },
    { id: "54", name: "말파이트", nameUs: "Malphite" },
    { id: "55", name: "카타리나", nameUs: "Katarina" },
    { id: "56", name: "녹턴", nameUs: "Nocturne" },
    { id: "57", name: "마오카이", nameUs: "Maokai" },
    { id: "58", name: "레넥톤", nameUs: "Renekton" },
    { id: "59", name: "자르반 4세", nameUs: "Jarvan IV" },
    { id: "60", name: "엘리스", nameUs: "Elise" },
    { id: "61", name: "오리아나", nameUs: "Orianna" },
    { id: "62", name: "오공", nameUs: "Wukong" },
    { id: "63", name: "브랜드", nameUs: "Brand" },
    { id: "64", name: "리 신", nameUs: "Lee Sin" },
    { id: "67", name: "베인", nameUs: "Vayne" },
    { id: "68", name: "럼블", nameUs: "Rumble" },
    { id: "69", name: "카시오페아", nameUs: "Cassiopeia" },
    { id: "72", name: "스카너", nameUs: "Skarner" },
    { id: "74", name: "하이머딩거", nameUs: "Heimerdinger" },
    { id: "75", name: "나서스", nameUs: "Nasus" },
    { id: "76", name: "니달리", nameUs: "Nidalee" },
    { id: "77", name: "우디르", nameUs: "Udyr" },
    { id: "78", name: "뽀삐", nameUs: "Poppy" },
    { id: "79", name: "그라가스", nameUs: "Gragas" },
    { id: "80", name: "판테온", nameUs: "Pantheon" },
    { id: "81", name: "이즈리얼", nameUs: "Ezreal" },
    { id: "82", name: "모데카이저", nameUs: "Mordekaiser" },
    { id: "83", name: "요릭", nameUs: "Yorick" },
    { id: "84", name: "아칼리", nameUs: "Akali" },
    { id: "85", name: "케넨", nameUs: "Kennen" },
    { id: "86", name: "가렌", nameUs: "Garen" },
    { id: "89", name: "레오나", nameUs: "Leona" },
    { id: "90", name: "말자하", nameUs: "Malzahar" },
    { id: "91", name: "탈론", nameUs: "Talon" },
    { id: "92", name: "리븐", nameUs: "Riven" },
    { id: "96", name: "코그모", nameUs: "Kog'Maw" },
    { id: "98", name: "쉔", nameUs: "Shen" },
    { id: "99", name: "럭스", nameUs: "Lux" },
    { id: "101", name: "제라스", nameUs: "Xerath" },
    { id: "102", name: "쉬바나", nameUs: "Shyvana" },
    { id: "103", name: "아리", nameUs: "Ahri" },
    { id: "104", name: "그레이브즈", nameUs: "Graves" },
    { id: "105", name: "피즈", nameUs: "Fizz" },
    { id: "106", name: "볼리베어", nameUs: "Volibear" },
    { id: "107", name: "렝가", nameUs: "Rengar" },
    { id: "110", name: "바루스", nameUs: "Varus" },
    { id: "111", name: "노틸러스", nameUs: "Nautilus" },
    { id: "112", name: "빅토르", nameUs: "Viktor" },
    { id: "113", name: "세주아니", nameUs: "Sejuani" },
    { id: "114", name: "피오라", nameUs: "Fiora" },
    { id: "115", name: "직스", nameUs: "Ziggs" },
    { id: "117", name: "룰루", nameUs: "Lulu" },
    { id: "119", name: "드레이븐", nameUs: "Draven" },
    { id: "120", name: "헤카림", nameUs: "Hecarim" },
    { id: "121", name: "카직스", nameUs: "Kha'Zix" },
    { id: "122", name: "다리우스", nameUs: "Darius" },
    { id: "126", name: "제이스", nameUs: "Jayce" },
    { id: "127", name: "리산드라", nameUs: "Lissandra" },
    { id: "131", name: "다이애나", nameUs: "Diana" },
    { id: "133", name: "퀸", nameUs: "Quinn" },
    { id: "134", name: "신드라", nameUs: "Syndra" },
    { id: "136", name: "아우렐리온 솔", nameUs: "Aurelion Sol" },
    { id: "141", name: "케인", nameUs: "Kayn" },
    { id: "142", name: "조이", nameUs: "Zoe" },
    { id: "143", name: "자이라", nameUs: "Zyra" },
    { id: "145", name: "카이사", nameUs: "Kai'Sa" },
    { id: "147", name: "세라핀", nameUs: "Seraphine" },
    { id: "150", name: "나르", nameUs: "Gnar" },
    { id: "154", name: "자크", nameUs: "Zac" },
    { id: "157", name: "야스오", nameUs: "Yasuo" },
    { id: "161", name: "벨코즈", nameUs: "Vel'Koz" },
    { id: "163", name: "탈리야", nameUs: "Taliyah" },
    { id: "164", name: "카밀", nameUs: "Camille" },
    { id: "166", name: "아크샨", nameUs: "Akshan" },
    { id: "200", name: "벨베스", nameUs: "Bel'Veth" },
    { id: "201", name: "브라움", nameUs: "Braum" },
    { id: "202", name: "진", nameUs: "Jhin" },
    { id: "203", name: "킨드레드", nameUs: "Kindred" },
    { id: "221", name: "제리", nameUs: "Zeri" },
    { id: "222", name: "징크스", nameUs: "Jinx" },
    { id: "223", name: "탐 켄치", nameUs: "Tahm Kench" },
    { id: "233", name: "브라이어", nameUs: "Briar" },
    { id: "234", name: "비에고", nameUs: "Viego" },
    { id: "235", name: "세나", nameUs: "Senna" },
    { id: "236", name: "루시안", nameUs: "Lucian" },
    { id: "238", name: "제드", nameUs: "Zed" },
    { id: "240", name: "클레드", nameUs: "Kled" },
    { id: "245", name: "에코", nameUs: "Ekko" },
    { id: "246", name: "키아나", nameUs: "Qiyana" },
    { id: "254", name: "바이", nameUs: "Vi" },
    { id: "266", name: "아트록스", nameUs: "Aatrox" },
    { id: "267", name: "나미", nameUs: "Nami" },
    { id: "268", name: "아지르", nameUs: "Azir" },
    { id: "350", name: "유미", nameUs: "Yuumi" },
    { id: "360", name: "사미라", nameUs: "Samira" },
    { id: "412", name: "쓰레쉬", nameUs: "Thresh" },
    { id: "420", name: "일라오이", nameUs: "Illaoi" },
    { id: "421", name: "렉사이", nameUs: "Rek'Sai" },
    { id: "427", name: "아이번", nameUs: "Ivern" },
    { id: "429", name: "칼리스타", nameUs: "Kalista" },
    { id: "432", name: "바드", nameUs: "Bard" },
    { id: "497", name: "라칸", nameUs: "Rakan" },
    { id: "498", name: "자야", nameUs: "Xayah" },
    { id: "516", name: "오른", nameUs: "Ornn" },
    { id: "517", name: "사일러스", nameUs: "Sylas" },
    { id: "518", name: "니코", nameUs: "Neeko" },
    { id: "523", name: "아펠리오스", nameUs: "Aphelios" },
    { id: "526", name: "렐", nameUs: "Rell" },
    { id: "555", name: "파이크", nameUs: "Pyke" },
    { id: "711", name: "벡스", nameUs: "Vex" },
    { id: "777", name: "요네", nameUs: "Yone" },
    { id: "799", name: "암베사", nameUs: "Ambessa" },
    { id: "800", name: "멜", nameUs: "Mel" },
    { id: "804", name: "유나라", nameUs: "Yunara" },
    { id: "875", name: "세트", nameUs: "Sett" },
    { id: "876", name: "릴리아", nameUs: "Lillia" },
    { id: "887", name: "그웬", nameUs: "Gwen" },
    { id: "888", name: "레나타 글라스크", nameUs: "Renata Glasc" },
    { id: "893", name: "오로라", nameUs: "Aurora" },
    { id: "895", name: "닐라", nameUs: "Nilah" },
    { id: "897", name: "크산테", nameUs: "K'Sante" },
    { id: "901", name: "스몰더", nameUs: "Smolder" },
    { id: "902", name: "밀리오", nameUs: "Milio" },
    { id: "904", name: "자헨", nameUs: "Zaahen" },
    { id: "910", name: "흐웨이", nameUs: "Hwei" },
    { id: "950", name: "나피리", nameUs: "Naafiri" }
  ],
  defaultLaneChampionIds: {
    top: [
      "54",
      "39",
      "14",
      "78",
      "24",
      "41",
      "2",
      "34",
      "98",
      "122",
      "126",
      "68",
      "84",
      "114",
      "58",
      "69",
      "85",
      "86",
      "133",
      "516",
      "19",
      "799",
      "27",
      "6",
      "80",
      "83",
      "67",
      "92",
      "150",
      "157",
      "164",
      "57",
      "240",
      "904",
      "517",
      "266",
      "154",
      "420",
      "74",
      "82",
      "875",
      "106",
      "79",
      "36",
      "17",
      "893",
      "75",
      "5",
      "110",
      "10",
      "23",
      "238",
      "777",
      "887",
      "50",
      "62",
      "31",
      "8",
      "13",
      "897",
      "223",
      "72",
      "48",
      "11"
    ],
    jungle: [
      "64",
      "950",
      "421",
      "56",
      "5",
      "104",
      "76",
      "254",
      "200",
      "60",
      "143",
      "233",
      "30",
      "517",
      "35",
      "72",
      "203",
      "20",
      "33",
      "28",
      "59",
      "154",
      "799",
      "113",
      "24",
      "245",
      "91",
      "904",
      "876",
      "120",
      "163",
      "19",
      "131",
      "11",
      "9",
      "121",
      "427",
      "80",
      "141",
      "105",
      "126",
      "102",
      "234",
      "62",
      "246",
      "57",
      "32",
      "106",
      "107",
      "78",
      "77",
      "98",
      "238",
      "36"
    ],
    mid: [
      "103",
      "142",
      "4",
      "7",
      "84",
      "711",
      "55",
      "127",
      "238",
      "101",
      "112",
      "34",
      "61",
      "910",
      "1",
      "80",
      "136",
      "246",
      "518",
      "131",
      "893",
      "45",
      "517",
      "105",
      "14",
      "950",
      "157",
      "166",
      "39",
      "126",
      "69",
      "54",
      "91",
      "3",
      "245",
      "63",
      "90",
      "134",
      "163",
      "50",
      "8",
      "99",
      "115",
      "234",
      "161",
      "20",
      "25",
      "777",
      "13",
      "38",
      "800",
      "268",
      "18",
      "901"
    ],
    bot: [
      "22",
      "222",
      "236",
      "15",
      "119",
      "51",
      "101",
      "18",
      "235",
      "21",
      "50",
      "498",
      "81",
      "360",
      "895",
      "202",
      "145",
      "67",
      "157",
      "523",
      "804",
      "29",
      "901",
      "69",
      "115",
      "96",
      "221",
      "110",
      "42",
      "429",
      "800"
    ],
    support: [
      "43",
      "412",
      "201",
      "111",
      "432",
      "53",
      "117",
      "526",
      "89",
      "60",
      "555",
      "147",
      "57",
      "12",
      "26",
      "44",
      "25",
      "78",
      "143",
      "40",
      "497",
      "267",
      "16",
      "37",
      "350",
      "235",
      "99",
      "223",
      "910",
      "161",
      "80",
      "9",
      "518",
      "63",
      "902",
      "50",
      "34",
      "35",
      "3",
      "101",
      "32",
      "7",
      "72",
      "517",
      "142",
      "164",
      "98",
      "800",
      "81"
    ]
  }
};
